# This file is responsible for maintaining services in docker for load balancing of different number of containers
version: "3" #Using version 3 of docker compose for services
services:
  redis:
    image: redis:5.0-alpine 
    ports: 
      - 32760:6379
    depends_on:
      - mongo
  mongodb:
    image: mongo:3.6.1
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 32761:27017
    command: mongod
volumes:
  mongodb:
  mongodb_config: